apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-depl
  labels:
    app: pma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
        - name: pma
          image: pma
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: pma-balancer
spec:
  selector:
    app: pma
  type: LoadBalancer
  ports:
    - name: http
      port: 5000
      targetPort: 5000
