apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-depl
  labels:
    app: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
        - name: wp
          image: wp
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: wp-balancer
spec:
  selector:
    app: wp
  type: LoadBalancer
  ports:
    - name: http
      port: 5050
      targetPort: 5050
